# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TaskRequest.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TaskRequest.proto',
  package='SVSE',
  syntax='proto3',
  serialized_options=b'\n\014ProtoMessageB\013TaskRequest',
  serialized_pb=b'\n\x11TaskRequest.proto\x12\x04SVSE\"\x91\x01\n\tOperation\x12\x0b\n\x03\x43md\x18\x01 \x01(\t\x12/\n\tParameter\x18\x02 \x03(\x0b\x32\x1c.SVSE.Operation.ParamOptions\x1a\x46\n\x0cParamOptions\x12\x14\n\x0csubparameter\x18\x01 \x01(\t\x12\r\n\x05owner\x18\x02 \x01(\t\x12\x11\n\trequestDL\x18\x03 \x01(\x03\"\xc1\x01\n\x0eServiceRequest\x12\x12\n\nDataSource\x18\x01 \x01(\t\x12\x16\n\x0eGlobalDeadline\x18\x02 \x01(\x03\x12\x0f\n\x07\x44\x61taTag\x18\x03 \x01(\t\x12\x0f\n\x07\x41rrival\x18\x04 \x01(\x03\x12\x0f\n\x07\x45stMean\x18\x05 \x01(\x01\x12\r\n\x05\x45stSD\x18\x06 \x01(\x01\x12\x10\n\x08Priority\x18\x07 \x01(\x05\x12\x0e\n\x06TaskID\x18\x08 \x01(\x03\x12\x1f\n\x06OPlist\x18\t \x03(\x0b\x32\x0f.SVSE.Operation\"\xcb\x01\n\x0cWorkerReport\x12\x12\n\nqueue_size\x18\x01 \x01(\x05\x12\x1b\n\x13queue_executionTime\x18\x02 \x01(\x03\x12\x15\n\rVMelapsedTime\x18\x03 \x01(\x03\x12\x12\n\nVMWorkTime\x18\x04 \x01(\x03\x12\x19\n\x11ontime_completion\x18\x05 \x01(\x03\x12\x11\n\tdl_missed\x18\x06 \x01(\x03\x12\x17\n\x0f\x63ompletedTaskID\x18\x07 \x03(\x03\x12\x18\n\x10weightedOvertime\x18\x08 \x01(\x01\"\x8f\x01\n\nTaskReport\x12\x17\n\x0f\x63ompletedTaskID\x18\x01 \x01(\x03\x12\x14\n\x0cworkerNodeID\x18\x02 \x01(\x05\x12\x15\n\rexecutionTime\x18\x03 \x01(\x01\x12\x11\n\ttimeStamp\x18\x04 \x01(\x01\x12(\n\ntheRequest\x18\x05 \x01(\x0b\x32\x14.SVSE.ServiceRequestB\x1b\n\x0cProtoMessageB\x0bTaskRequestb\x06proto3'
)




_OPERATION_PARAMOPTIONS = _descriptor.Descriptor(
  name='ParamOptions',
  full_name='SVSE.Operation.ParamOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subparameter', full_name='SVSE.Operation.ParamOptions.subparameter', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='owner', full_name='SVSE.Operation.ParamOptions.owner', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requestDL', full_name='SVSE.Operation.ParamOptions.requestDL', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=173,
)

_OPERATION = _descriptor.Descriptor(
  name='Operation',
  full_name='SVSE.Operation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Cmd', full_name='SVSE.Operation.Cmd', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Parameter', full_name='SVSE.Operation.Parameter', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_OPERATION_PARAMOPTIONS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=173,
)


_SERVICEREQUEST = _descriptor.Descriptor(
  name='ServiceRequest',
  full_name='SVSE.ServiceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='DataSource', full_name='SVSE.ServiceRequest.DataSource', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='GlobalDeadline', full_name='SVSE.ServiceRequest.GlobalDeadline', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DataTag', full_name='SVSE.ServiceRequest.DataTag', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Arrival', full_name='SVSE.ServiceRequest.Arrival', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='EstMean', full_name='SVSE.ServiceRequest.EstMean', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='EstSD', full_name='SVSE.ServiceRequest.EstSD', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Priority', full_name='SVSE.ServiceRequest.Priority', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TaskID', full_name='SVSE.ServiceRequest.TaskID', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='OPlist', full_name='SVSE.ServiceRequest.OPlist', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=369,
)


_WORKERREPORT = _descriptor.Descriptor(
  name='WorkerReport',
  full_name='SVSE.WorkerReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='queue_size', full_name='SVSE.WorkerReport.queue_size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='queue_executionTime', full_name='SVSE.WorkerReport.queue_executionTime', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='VMelapsedTime', full_name='SVSE.WorkerReport.VMelapsedTime', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='VMWorkTime', full_name='SVSE.WorkerReport.VMWorkTime', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ontime_completion', full_name='SVSE.WorkerReport.ontime_completion', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dl_missed', full_name='SVSE.WorkerReport.dl_missed', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='completedTaskID', full_name='SVSE.WorkerReport.completedTaskID', index=6,
      number=7, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weightedOvertime', full_name='SVSE.WorkerReport.weightedOvertime', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=372,
  serialized_end=575,
)


_TASKREPORT = _descriptor.Descriptor(
  name='TaskReport',
  full_name='SVSE.TaskReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='completedTaskID', full_name='SVSE.TaskReport.completedTaskID', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='workerNodeID', full_name='SVSE.TaskReport.workerNodeID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='executionTime', full_name='SVSE.TaskReport.executionTime', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='SVSE.TaskReport.timeStamp', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='theRequest', full_name='SVSE.TaskReport.theRequest', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=578,
  serialized_end=721,
)

_OPERATION_PARAMOPTIONS.containing_type = _OPERATION
_OPERATION.fields_by_name['Parameter'].message_type = _OPERATION_PARAMOPTIONS
_SERVICEREQUEST.fields_by_name['OPlist'].message_type = _OPERATION
_TASKREPORT.fields_by_name['theRequest'].message_type = _SERVICEREQUEST
DESCRIPTOR.message_types_by_name['Operation'] = _OPERATION
DESCRIPTOR.message_types_by_name['ServiceRequest'] = _SERVICEREQUEST
DESCRIPTOR.message_types_by_name['WorkerReport'] = _WORKERREPORT
DESCRIPTOR.message_types_by_name['TaskReport'] = _TASKREPORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Operation = _reflection.GeneratedProtocolMessageType('Operation', (_message.Message,), {

  'ParamOptions' : _reflection.GeneratedProtocolMessageType('ParamOptions', (_message.Message,), {
    'DESCRIPTOR' : _OPERATION_PARAMOPTIONS,
    '__module__' : 'TaskRequest_pb2'
    # @@protoc_insertion_point(class_scope:SVSE.Operation.ParamOptions)
    })
  ,
  'DESCRIPTOR' : _OPERATION,
  '__module__' : 'TaskRequest_pb2'
  # @@protoc_insertion_point(class_scope:SVSE.Operation)
  })
_sym_db.RegisterMessage(Operation)
_sym_db.RegisterMessage(Operation.ParamOptions)

ServiceRequest = _reflection.GeneratedProtocolMessageType('ServiceRequest', (_message.Message,), {
  'DESCRIPTOR' : _SERVICEREQUEST,
  '__module__' : 'TaskRequest_pb2'
  # @@protoc_insertion_point(class_scope:SVSE.ServiceRequest)
  })
_sym_db.RegisterMessage(ServiceRequest)

WorkerReport = _reflection.GeneratedProtocolMessageType('WorkerReport', (_message.Message,), {
  'DESCRIPTOR' : _WORKERREPORT,
  '__module__' : 'TaskRequest_pb2'
  # @@protoc_insertion_point(class_scope:SVSE.WorkerReport)
  })
_sym_db.RegisterMessage(WorkerReport)

TaskReport = _reflection.GeneratedProtocolMessageType('TaskReport', (_message.Message,), {
  'DESCRIPTOR' : _TASKREPORT,
  '__module__' : 'TaskRequest_pb2'
  # @@protoc_insertion_point(class_scope:SVSE.TaskReport)
  })
_sym_db.RegisterMessage(TaskReport)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
